### ISSUE TITLE
code in comment make the highlighting less happy

### ISSUE THREAD

**Issue by fponticelli** [vshaxe/haxe-TmLanguage#15]
See attached image.

<img width="689" alt="screen shot 2017-02-20 at 12 55 29 pm" src="https://cloud.githubusercontent.com/assets/163915/23140199/79d954f6-f76d-11e6-99ec-13078540e6a9.png">

**Comment by Gama11** [comment]
Hm, that looks pretty off even before the comment... Latest vshaxe? What theme are you using?

Can you provide the source to copy-paste for easy testing?

**Comment by fponticelli** [comment]
1.3.3 of VSCode and the theme was a stock dark. With other themes the `function` keyword is fine but the section after the comment is broken in the same way.

**Comment by Gama11** [comment]
Can you provide the source to copy-paste for easy testing?

**Comment by fponticelli** [comment]
```haxe
  static function refreshSlug(slug: Slug) {
    var id = slug.toString(),
        url = js.Browser.window.location.href, // '${Loc.msg.site_url}/#${slug.toString()}';
        title = js.Browser.document.title;
    try {
      (untyped __js__("DISQUS")).reset({
        reload: true,
        config: function () {
          var self = js.Lib.nativeThis;
          self.page.identifier = id;
          self.page.url = url;
          self.page.title = title;
        }
      });
    } catch(e: Dynamic) {
      haxe.Timer.delay(refreshSlug.bind(slug), 25);
    }
  }
```

**Comment by Gama11** [comment]
Thanks, I can reproduce it. :)

I guess you're using the "Dark" theme rather than Dark+, which is why it looked off to me.

**Comment by Gama11** [comment]
This is actually just about comments (or conditional compilation statements for that matter) not being highlighted in multi-var decls.
