### ISSUE TITLE
Invalid string interpolation

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/haxe-TmLanguage#27]
The compiler does not interpolate invalid identifiers (e.g. starting with number)

<img width="50" alt="screen shot 2017-06-01 at 11 31 24 am" src="https://cloud.githubusercontent.com/assets/1103788/26663531/e645d2e6-46bd-11e7-8e63-dee1f5a5947e.png">

`'$1'` should not be highlighted as interpolation.

**Comment by Gama11** [comment]
Nice catch. :)
