### ISSUE TITLE
Highlight inline templates (jsx/hxx/html, etc)

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/haxe-TmLanguage#28]
I see language-haxe (atom) [did it](https://github.com/jeremyfa/language-haxe/blob/548e353412b2b1700c5f1365f1d3f2868be85106/grammars/haxe-grammars.cson#L448) ([screenshot](https://github.com/massiveinteractive/haxe-react/issues/23#issue-142219462))
So I think it is possible to do.

Or let me know where to start from, I may give it a try.

**Comment by Gama11** [comment]
I'm not sure that should be part of this repo, it's not exactly part of Haxe, rather third-party frameworks.

**Comment by kevinresol** [comment]
> I'm not sure that should be part of this repo, it's not exactly part of Haxe, rather third-party frameworks.

No problem, but I wonder if I create a new extension for that, will it be able to coexist with vshaxe?

**Comment by Gama11** [comment]
That's a good question. I think you may be able override the Haxe grammar if you have an extension that is loaded after vshaxe, but extension loading order is undefined. It would be cleaner to create a new language ID (`haxe-react` or whatever) and then remap `.hx` to that in haxe-react projects in `settings.json`.

 https://github.com/vshaxe/vshaxe/blob/1.7.0/package.json#L197-L230

```json
"files.associations": {
    "*.hx": "haxe-react"
}
```

Also, I don't think it's necessary to duplicate the entire Haxe grammar - you can include reference / include other grammars (there may even be a jsx one you can reuse that way). For instance, we do that to achieve Haxe highlighting in .hxml files after `--macro`:

https://github.com/vshaxe/haxe-TmLanguage/blob/4f320e79597e3a9856127add6b3357c072f01b2f/hxml.YAML-tmLanguage#L18

There's another (simple) example here:

https://github.com/vshaxe/vshaxe-debug-tools/blob/master/syntaxes/hxtest.json

**Comment by Gama11** [comment]
Note: separate language IDs seems to be the approach that VSCode has taken for JS / TS as well:

![](http://i.imgur.com/uGnkfuD.png)

![](http://i.imgur.com/BNF5hDt.png)

**Comment by kevinresol** [comment]
Thanks for the info. I will take care of them :)

**Comment by nadako** [comment]
But will vshaxe activate for custom langs?

**Comment by Gama11** [comment]
@nadako Why does it need to activate if this is implemented via a separate extension?

**Comment by Gama11** [comment]
Oh, for completion etc of course. Hm...

**Comment by Gama11** [comment]
Considering #30 is closed, this can probably be closed too.

**Comment by kevinresol** [comment]
I don't mind if this extension doesn't do the actual highlighting. But at least we need a mechanism. Especially when [inline markup](https://github.com/HaxeFoundation/haxe-evolution/pull/26) _may_ become a standard feature. Shall we reopen and let the discussion go on?

**Comment by djaonourside** [comment]
Hi, guys! A supporting jsx hightlight and go to definition action is very necessary. So it's unconvenient to use vscode in haxe-react projects. HaxeDevelop can do this things but it runs on windows only.
