### ISSUE TITLE
Doubly nested parens in conditional compilation

### ISSUE THREAD

**Issue by Gama11** [vshaxe/haxe-TmLanguage#5]
```haxe
#if (((foo)) && bar)
#end
```

![](http://i.imgur.com/P12vnbu.png)

**Comment by Simn** [comment]
Can this even be solved with that regex approach? It's the classic example of a non-regular language because you can't count the parens in a regex.

**Comment by Gama11** [comment]
Yes, because tmLanguage is not just "flat list" of regexes, they're hierarchical / scoped. I.e. you can say:

- define a rule called "paren"
  - match `(`
  - match against some rules, including "paren"
  - match `)`

If this didn't work, highlighting would be a lot worse in general. :) I think this is just an oversight in the conditional compilation rules specifically.
