### ISSUE TITLE
Haxe highlighting not working properly

### ISSUE THREAD

**Issue by Sword352** [vshaxe/haxe-TmLanguage#55]
Hi, the haxe highlighting doesnt work properly for some reason, i would like to get help. I installed every extensions, but it doesnt work properly. The output says that the haxe language server runs fine.

![image](https://user-images.githubusercontent.com/99792114/204855359-175243dc-b9ed-4665-a793-5e7edaad4db5.png)
![image](https://user-images.githubusercontent.com/99792114/204855413-40638ce1-7ba2-4be9-9929-c104987000a0.png)
![image](https://user-images.githubusercontent.com/99792114/204855463-e8b6be4b-ab8a-4d82-9cb5-fa5135443f83.png)

Windows 11 22H2

**Comment by Gama11** [comment]
You don't say what the problem is. The highlighting in your screenshot is not very colorful, but that could just be a custom theme you're using?

**Comment by Sword352** [comment]
> You don't say what the problem is. The highlighting in your screenshot is not very colorful, but that could just be a custom theme you're using?

i didnt installed a custom theme

**Comment by Gama11** [comment]
Well, what theme do you have selected?

**Comment by AlexHaxe** [comment]
works just fine on Linux with latest vscode / vshaxe.:
![Screenshot_20221201_171254](https://user-images.githubusercontent.com/7204032/205103645-481cf6e5-8826-4504-a815-50144e8bbde5.png)

so it must be something on your end. try a different theme and check your settings (global and local).

**Comment by Sword352** [comment]
> works just fine on Linux with latest vscode / vshaxe.: ![Screenshot_20221201_171254](https://user-images.githubusercontent.com/7204032/205103645-481cf6e5-8826-4504-a815-50144e8bbde5.png)
> 
> so it must be something on your end. try a different theme and check your settings (global and local).

Alright, Thank you!
I fixed it, basically i was just needing to use the dark+ instead of the dark theme (both included on visual studio code).
